version: '3.8'

services:
  #ALL DATABASES AND ADMINER, MONGO-EXPRESS
  adminer:
    extends:
      file: ./compose/docker-compose-db.yml
      service: adminer

  # mongo:
  #   extends:
  #     file: ./compose/docker-compose-db.yml
  #     service: mongo
  
  # postgres:
  #   extends:
  #     file: ./compose/docker-compose-db.yml
  #     service: postgres

  training-db:
    extends:
      file: ./compose/docker-compose-db.yml
      service: training-db

  #ALL APIs
  # analytic-api:
  #   extends:
  #     file: ./compose/docker-compose-service.yml
  #     service: analytic-api

  training-api:
    extends:
      file: ./compose/docker-compose-service.yml
      service: training-api
  
  # nutrition-api:
  #   extends:
  #     file: ./compose/docker-compose-service.yml
  #     service: nutrition-api

  # users-api:
  #   extends:
  #     file: ./compose/docker-compose-service.yml
  #     service: users-api

  # auth-api:
  #   extends:
  #     file: ./compose/docker-compose-service.yml
  #     service: auth-api
  
