#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../prisma@4.12.0/node_modules/prisma/build/index.js" "$@"
else
  exec node  "$basedir/../../../../../../prisma@4.12.0/node_modules/prisma/build/index.js" "$@"
fi
