const finals = [
  {
    name: 'tomates',
    calories: 18.5,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.9,
    sodium_mg: 5,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.9,
    fiber_g: 1.2,
    sugar_g: 2.6,
  },
  {
    name: 'mangues',
    calories: 58.7,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 0.8,
    sodium_mg: 1,
    potassium_mg: 13,
    cholesterol_mg: 0,
    carbohydrates_total_g: 15.1,
    fiber_g: 1.6,
    sugar_g: 13.7,
  },
  {
    name: 'framboises',
    calories: 51.8,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0,
    protein_g: 1,
    sodium_mg: 0,
    potassium_mg: 28,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12,
    fiber_g: 6.4,
    sugar_g: 4.5,
  },
  {
    name: 'pommes',
    calories: 53.4,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.3,
    sodium_mg: 1,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.8,
    fiber_g: 2.4,
    sugar_g: 10.3,
  },
  {
    name: 'oranges',
    calories: 49.8,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0.9,
    sodium_mg: 1,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12.5,
    fiber_g: 2.2,
    sugar_g: 8.6,
  },
  {
    name: 'kiwi',
    calories: 59.5,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0,
    protein_g: 1.1,
    sodium_mg: 3,
    potassium_mg: 33,
    cholesterol_mg: 0,
    carbohydrates_total_g: 14.9,
    fiber_g: 3,
    sugar_g: 9.1,
  },
  {
    name: 'noix de coco',
    calories: 450.1,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 27.9,
    fat_saturated_g: 26.6,
    protein_g: 3.1,
    sodium_mg: 282,
    potassium_mg: 100,
    cholesterol_mg: 0,
    carbohydrates_total_g: 51.6,
    fiber_g: 9.7,
    sugar_g: 36.8,
  },
  {
    name: 'raisins',
    calories: 69.6,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    protein_g: 0.7,
    sodium_mg: 2,
    potassium_mg: 20,
    cholesterol_mg: 0,
    carbohydrates_total_g: 18.1,
    fiber_g: 0.9,
    sugar_g: 15.5,
  },
  {
    name: 'citrons',
    calories: 28.5,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    protein_g: 1.1,
    sodium_mg: 2,
    potassium_mg: 16,
    cholesterol_mg: 0,
    carbohydrates_total_g: 9.4,
    fiber_g: 2.8,
    sugar_g: 2.5,
  },
  {
    name: 'fraises',
    calories: 31.3,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    protein_g: 0.7,
    sodium_mg: 1,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.6,
    fiber_g: 2,
    sugar_g: 4.9,
  },
  {
    name: 'pamplemousses',
    calories: 43.2,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0.8,
    sodium_mg: 0,
    potassium_mg: 18,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.7,
    fiber_g: 1.6,
    sugar_g: 6.9,
  },
  {
    name: 'pêches',
    calories: 39.5,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.9,
    sodium_mg: 0,
    potassium_mg: 19,
    cholesterol_mg: 0,
    carbohydrates_total_g: 9.7,
    fiber_g: 1.5,
    sugar_g: 8.4,
  },
  {
    name: 'myrtilles',
    calories: 55.7,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.7,
    sodium_mg: 0,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 14.8,
    fiber_g: 2.2,
    sugar_g: 10.3,
  },
  {
    name: 'melons',
    calories: 33.6,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    protein_g: 0.8,
    sodium_mg: 16,
    potassium_mg: 14,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.1,
    fiber_g: 0.9,
    sugar_g: 7.8,
  },
  {
    name: 'citrons verts',
    calories: 29.4,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.7,
    sodium_mg: 2,
    potassium_mg: 17,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.7,
    fiber_g: 2.8,
    sugar_g: 1.7,
  },
  {
    name: 'pastèques',
    calories: 30.2,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.6,
    sodium_mg: 0,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.5,
    fiber_g: 0.4,
    sugar_g: 6.2,
  },
  {
    name: 'prunes',
    calories: 46.6,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    protein_g: 0.7,
    sodium_mg: 0,
    potassium_mg: 15,
    cholesterol_mg: 0,
    carbohydrates_total_g: 11.6,
    fiber_g: 1.4,
    sugar_g: 9.9,
  },
  {
    name: 'avocats',
    calories: 171.9,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 15.3,
    fat_saturated_g: 2.1,
    protein_g: 2,
    sodium_mg: 7,
    potassium_mg: 53,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.6,
    fiber_g: 6.7,
    sugar_g: 0.3,
  },
  {
    name: 'bananes',
    calories: 87.4,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    protein_g: 1.1,
    sodium_mg: 1,
    potassium_mg: 22,
    cholesterol_mg: 0,
    carbohydrates_total_g: 22.4,
    fiber_g: 2.6,
    sugar_g: 12.2,
  },
  {
    name: 'ananas',
    calories: 51.3,
    category: 1,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0.5,
    sodium_mg: 1,
    potassium_mg: 8,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.1,
    fiber_g: 1.4,
    sugar_g: 9.9,
  },
  {
    name: 'laitue',
    calories: 17,
    category: 2,

    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    protein_g: 1.2,
    sodium_mg: 7,
    potassium_mg: 30,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.3,
    fiber_g: 2.1,
    sugar_g: 1.2,
  },
  {
    name: 'concombres',
    category: 2,
    calories: 15.1,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0.7,
    sodium_mg: 1,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.6,
    fiber_g: 0.5,
    sugar_g: 1.7,
  },
  {
    name: 'brocolis',
    category: 2,
    calories: 35,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 2.4,
    sodium_mg: 41,
    potassium_mg: 65,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.3,
    fiber_g: 3.3,
    sugar_g: 1.4,
  },
  {
    name: 'haricots',
    category: 2,
    calories: 91.3,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 4.7,
    sodium_mg: 339,
    potassium_mg: 75,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21.3,
    fiber_g: 4.1,
    sugar_g: 7.9,
  },
  {
    name: 'petits pois',
    category: 2,
    calories: 82.4,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 5.4,
    sodium_mg: 3,
    potassium_mg: 117,
    cholesterol_mg: 0,
    carbohydrates_total_g: 15.9,
    fiber_g: 5.4,
    sugar_g: 5.9,
  },
  {
    name: 'chou-fleur',
    category: 2,
    calories: 22.4,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0.1,
    protein_g: 1.8,
    sodium_mg: 14,
    potassium_mg: 31,
    cholesterol_mg: 0,
    carbohydrates_total_g: 4.1,
    fiber_g: 2.3,
    sugar_g: 2.1,
  },
  {
    name: 'poivrons',
    category: 2,
    calories: 27.6,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.9,
    sodium_mg: 2,
    potassium_mg: 17,
    cholesterol_mg: 0,
    carbohydrates_total_g: 6.7,
    fiber_g: 1.2,
    sugar_g: 3.2,
  },
  {
    name: 'carottes',
    category: 2,
    calories: 35.1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.8,
    sodium_mg: 56,
    potassium_mg: 30,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.1,
    fiber_g: 3,
    sugar_g: 3.4,
  },
  {
    name: 'patates douces',
    category: 2,
    calories: 75.9,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 1.4,
    sodium_mg: 27,
    potassium_mg: 32,
    cholesterol_mg: 0,
    carbohydrates_total_g: 17.6,
    fiber_g: 2.5,
    sugar_g: 5.8,
  },
  {
    name: 'ail',
    category: 2,
    calories: 144.8,
    serving_size_g: 100,
    fat_total_g: 0.7,
    fat_saturated_g: 0,
    protein_g: 6.4,
    sodium_mg: 16,
    potassium_mg: 153,
    cholesterol_mg: 0,
    carbohydrates_total_g: 32.5,
    fiber_g: 2,
    sugar_g: 1,
  },
  {
    name: 'choux',
    category: 2,
    calories: 23.4,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 1.3,
    sodium_mg: 7,
    potassium_mg: 32,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.5,
    fiber_g: 1.9,
    sugar_g: 2.8,
  },
  {
    name: 'aubergines',
    category: 2,
    calories: 35.5,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0.8,
    sodium_mg: 0,
    potassium_mg: 15,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.9,
    fiber_g: 2.5,
    sugar_g: 3.2,
  },
  {
    name: 'maïs',
    category: 2,
    calories: 93.9,
    serving_size_g: 100,
    fat_total_g: 1.5,
    fat_saturated_g: 0.2,
    protein_g: 3.4,
    sodium_mg: 1,
    potassium_mg: 75,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21,
    fiber_g: 2.4,
    sugar_g: 4.6,
  },
  {
    name: 'champignons',
    category: 2,
    calories: 27.9,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0.1,
    protein_g: 2.2,
    sodium_mg: 1,
    potassium_mg: 86,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.2,
    fiber_g: 2.2,
    sugar_g: 2.3,
  },
  {
    name: 'oignons',
    category: 2,
    calories: 44.5,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 1.4,
    sodium_mg: 3,
    potassium_mg: 35,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.2,
    fiber_g: 1.4,
    sugar_g: 4.8,
  },
  {
    name: 'chou frisé',
    category: 2,
    calories: 27.2,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 1.9,
    sodium_mg: 23,
    potassium_mg: 28,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.6,
    fiber_g: 2,
    sugar_g: 1.3,
  },
  {
    name: 'épinards',
    category: 2,
    calories: 23.3,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    protein_g: 2.9,
    sodium_mg: 69,
    potassium_mg: 55,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.8,
    fiber_g: 2.4,
    sugar_g: 0.4,
  },
  {
    name: 'courgettes',
    category: 2,
    calories: 14.7,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 1.1,
    sodium_mg: 3,
    potassium_mg: 37,
    cholesterol_mg: 0,
    carbohydrates_total_g: 2.7,
    fiber_g: 1,
    sugar_g: 1.7,
  },
  {
    name: 'gingembre',
    category: 2,
    calories: 78.3,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0,
    protein_g: 2,
    sodium_mg: 13,
    potassium_mg: 34,
    cholesterol_mg: 0,
    carbohydrates_total_g: 18.3,
    fiber_g: 2,
    sugar_g: 1.5,
  },
  {
    name: 'pommes de terre',
    category: 2,
    calories: 92.9,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 2.5,
    sodium_mg: 10,
    potassium_mg: 70,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21,
    fiber_g: 2.2,
    sugar_g: 1.2,
  },
  {
    name: 'filets de poisson',
    calories: 106.2,
    category: 3,
    serving_size_g: 100,
    fat_total_g: 0.9,
    fat_saturated_g: 0.2,
    protein_g: 23.6,
    sodium_mg: 112,
    potassium_mg: 181,
    cholesterol_mg: 94,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'poulet',
    calories: 222.6,
    category: 3,

    serving_size_g: 100,
    fat_total_g: 12.9,
    fat_saturated_g: 3.7,
    protein_g: 23.7,
    sodium_mg: 72,
    potassium_mg: 179,
    cholesterol_mg: 92,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'bœuf',
    calories: 291.9,
    category: 3,

    serving_size_g: 100,
    fat_total_g: 19.7,
    fat_saturated_g: 7.8,
    protein_g: 26.6,
    sodium_mg: 63,
    potassium_mg: 206,
    cholesterol_mg: 87,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'agneau',
    category: 3,

    calories: 301.2,
    serving_size_g: 100,
    fat_total_g: 20.5,
    fat_saturated_g: 8.8,
    protein_g: 24.4,
    sodium_mg: 71,
    potassium_mg: 187,
    cholesterol_mg: 98,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'bacon',
    category: 3,
    calories: 466.4,
    serving_size_g: 100,
    fat_total_g: 34.9,
    fat_saturated_g: 12,
    protein_g: 34,
    sodium_mg: 1674,
    potassium_mg: 380,
    cholesterol_mg: 98,
    carbohydrates_total_g: 1.7,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'jambon',
    category: 3,
    calories: 141.6,
    serving_size_g: 100,
    fat_total_g: 5.1,
    fat_saturated_g: 0.9,
    protein_g: 22.2,
    sodium_mg: 968,
    potassium_mg: 305,
    cholesterol_mg: 64,
    carbohydrates_total_g: 1,
    fiber_g: 0,
    sugar_g: 1.1,
  },
  {
    name: 'coquilles Saint-Jacques',
    category: 3,
    calories: 110.3,
    serving_size_g: 100,
    fat_total_g: 0.9,
    fat_saturated_g: 0.2,
    protein_g: 20.5,
    sodium_mg: 660,
    potassium_mg: 421,
    cholesterol_mg: 40,
    carbohydrates_total_g: 5.4,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'thon',
    category: 3,
    calories: 133.3,
    serving_size_g: 100,
    fat_total_g: 0.6,
    fat_saturated_g: 0.2,
    protein_g: 29.4,
    sodium_mg: 54,
    potassium_mg: 331,
    cholesterol_mg: 46,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'saucisses',
    category: 3,
    calories: 323.2,
    serving_size_g: 100,
    fat_total_g: 26.9,
    fat_saturated_g: 8.7,
    protein_g: 18.6,
    sodium_mg: 808,
    potassium_mg: 150,
    cholesterol_mg: 86,
    carbohydrates_total_g: 1.4,
    fiber_g: 0,
    sugar_g: 1.1,
  },
  {
    name: 'viande de crabe',
    category: 3,
    calories: 80.5,
    serving_size_g: 100,
    fat_total_g: 0.7,
    fat_saturated_g: 0.2,
    protein_g: 17.9,
    sodium_mg: 402,
    potassium_mg: 235,
    cholesterol_mg: 98,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'steak',
    category: 3,
    calories: 273.4,
    serving_size_g: 100,
    fat_total_g: 18.8,
    fat_saturated_g: 7.3,
    protein_g: 26,
    sodium_mg: 52,
    potassium_mg: 194,
    cholesterol_mg: 95,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'saumon',
    category: 3,
    calories: 208.7,
    serving_size_g: 100,
    fat_total_g: 12.1,
    fat_saturated_g: 2.4,
    protein_g: 22,
    sodium_mg: 61,
    potassium_mg: 253,
    cholesterol_mg: 63,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'crevettes',
    category: 3,
    calories: 118.7,
    serving_size_g: 100,
    fat_total_g: 1.8,
    fat_saturated_g: 0.6,
    protein_g: 22.8,
    sodium_mg: 930,
    potassium_mg: 307,
    cholesterol_mg: 208,
    carbohydrates_total_g: 1.6,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    category: 3,
    name: 'porc',
    calories: 236.2,
    serving_size_g: 100,
    fat_total_g: 14,
    fat_saturated_g: 4.9,
    protein_g: 26.2,
    sodium_mg: 57,
    potassium_mg: 219,
    cholesterol_mg: 88,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'travers de porc',
    category: 3,
    calories: 361.3,
    serving_size_g: 100,
    fat_total_g: 30.9,
    fat_saturated_g: 9.2,
    protein_g: 21.1,
    sodium_mg: 91,
    potassium_mg: 159,
    cholesterol_mg: 103,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'foie',
    category: 3,
    calories: 169.8,
    serving_size_g: 100,
    fat_total_g: 6.6,
    fat_saturated_g: 2.1,
    protein_g: 24.4,
    sodium_mg: 77,
    potassium_mg: 407,
    cholesterol_mg: 563,
    carbohydrates_total_g: 0.9,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'boulettes de viande',
    category: 3,
    calories: 289.2,
    serving_size_g: 100,
    fat_total_g: 21.8,
    fat_saturated_g: 7.7,
    protein_g: 14.5,
    sodium_mg: 662,
    potassium_mg: 243,
    cholesterol_mg: 66,
    carbohydrates_total_g: 8.1,
    fiber_g: 2.3,
    sugar_g: 3.5,
  },
  {
    name: 'dinde',
    calories: 193.1,
    category: 3,
    serving_size_g: 100,
    fat_total_g: 7.4,
    fat_saturated_g: 2.2,
    protein_g: 28.6,
    sodium_mg: 104,
    potassium_mg: 226,
    cholesterol_mg: 110,
    carbohydrates_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'viande hachée',
    category: 3,
    calories: 266.2,
    serving_size_g: 100,
    fat_total_g: 17.5,
    fat_saturated_g: 6.6,
    protein_g: 26.9,
    sodium_mg: 89,
    potassium_mg: 225,
    cholesterol_mg: 89,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'homard',
    category: 3,
    calories: 143.7,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 0.3,
    protein_g: 26.5,
    sodium_mg: 224,
    potassium_mg: 229,
    cholesterol_mg: 89,
    carbohydrates_total_g: 3.1,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'gouda',
    category: 3,
    calories: 345.6,
    serving_size_g: 100,
    fat_total_g: 27.4,
    fat_saturated_g: 17.5,
    protein_g: 25.1,
    sodium_mg: 830,
    potassium_mg: 555,
    cholesterol_mg: 111,
    carbohydrates_total_g: 2.3,
    fiber_g: 0,
    sugar_g: 2.2,
  },
  {
    name: 'mozzarella',
    category: 4,

    calories: 295.5,
    serving_size_g: 100,
    fat_total_g: 22.6,
    fat_saturated_g: 13.1,
    protein_g: 22.1,
    sodium_mg: 629,
    potassium_mg: 350,
    cholesterol_mg: 79,
    carbohydrates_total_g: 2.2,
    fiber_g: 0,
    sugar_g: 1,
  },
  {
    name: 'cheddar',
    calories: 415.6,
    category: 4,

    serving_size_g: 100,
    fat_total_g: 33.9,
    fat_saturated_g: 18.8,
    protein_g: 22.8,
    sodium_mg: 640,
    potassium_mg: 455,
    cholesterol_mg: 97,
    carbohydrates_total_g: 3.1,
    fiber_g: 0,
    sugar_g: 0.5,
  },
  {
    name: 'fromage de chèvre',
    category: 4,
    calories: 363.6,
    serving_size_g: 100,
    fat_total_g: 29.5,
    fat_saturated_g: 20.7,
    protein_g: 21.7,
    sodium_mg: 418,
    potassium_mg: 380,
    cholesterol_mg: 77,
    carbohydrates_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 0.1,
  },
  {
    name: 'lait',
    category: 4,
    calories: 51.3,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 1.2,
    protein_g: 3.5,
    sodium_mg: 52,
    potassium_mg: 100,
    cholesterol_mg: 8,
    carbohydrates_total_g: 4.9,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'crème',
    calories: 347.4,
    category: 4,

    serving_size_g: 100,
    fat_total_g: 35.6,
    fat_saturated_g: 22.9,
    protein_g: 2.9,
    sodium_mg: 27,
    potassium_mg: 57,
    cholesterol_mg: 111,
    carbohydrates_total_g: 2.8,
    fiber_g: 0,
    sugar_g: 2.9,
  },
  {
    name: 'feta',
    calories: 260.8,
    category: 4,

    serving_size_g: 100,
    fat_total_g: 21.1,
    fat_saturated_g: 14.8,
    protein_g: 14.2,
    sodium_mg: 899,
    potassium_mg: 343,
    cholesterol_mg: 88,
    carbohydrates_total_g: 4.1,
    fiber_g: 0,
    sugar_g: 4.1,
  },
  {
    name: 'parmesan',
    category: 4,
    calories: 419.3,
    serving_size_g: 100,
    fat_total_g: 27.6,
    fat_saturated_g: 15.4,
    protein_g: 28.6,
    sodium_mg: 1811,
    potassium_mg: 635,
    cholesterol_mg: 85,
    carbohydrates_total_g: 14.1,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'yaourt',
    category: 4,
    calories: 64.2,
    serving_size_g: 100,
    fat_total_g: 1.6,
    fat_saturated_g: 1,
    protein_g: 5.3,
    sodium_mg: 69,
    potassium_mg: 145,
    cholesterol_mg: 5,
    carbohydrates_total_g: 7.2,
    fiber_g: 0,
    sugar_g: 7.1,
  },
  {
    name: 'fromage',
    category: 4,
    calories: 393.9,
    serving_size_g: 100,
    fat_total_g: 33,
    fat_saturated_g: 18.9,
    protein_g: 22.7,
    sodium_mg: 661,
    potassium_mg: 459,
    cholesterol_mg: 100,
    carbohydrates_total_g: 3.2,
    fiber_g: 0,
    sugar_g: 0.5,
  },
  {
    name: 'ricotta',
    category: 4,
    calories: 134,
    serving_size_g: 100,
    fat_total_g: 8.1,
    fat_saturated_g: 4.9,
    protein_g: 11.3,
    sodium_mg: 100,
    potassium_mg: 180,
    cholesterol_mg: 31,
    carbohydrates_total_g: 5.1,
    fiber_g: 0,
    sugar_g: 0.3,
  },
  {
    name: 'fromage blanc',
    category: 4,
    calories: 98.3,
    serving_size_g: 100,
    fat_total_g: 4.3,
    fat_saturated_g: 1.7,
    protein_g: 11.2,
    sodium_mg: 370,
    potassium_mg: 161,
    cholesterol_mg: 16,
    carbohydrates_total_g: 3.4,
    fiber_g: 0,
    sugar_g: 2.7,
  },
  {
    name: 'fromage bleu',
    category: 4,
    calories: 346.9,
    serving_size_g: 100,
    fat_total_g: 28.9,
    fat_saturated_g: 18.5,
    protein_g: 21.6,
    sodium_mg: 1156,
    potassium_mg: 384,
    cholesterol_mg: 76,
    carbohydrates_total_g: 2.3,
    fiber_g: 0,
    sugar_g: 0.5,
  },
  {
    name: 'camembert',
    category: 4,
    calories: 293.2,
    serving_size_g: 100,
    fat_total_g: 24.1,
    fat_saturated_g: 15.4,
    protein_g: 19.9,
    sodium_mg: 826,
    potassium_mg: 349,
    cholesterol_mg: 70,
    carbohydrates_total_g: 0.5,
    fiber_g: 0,
    sugar_g: 0.5,
  },
  {
    name: 'crème fouettée',
    category: 4,
    calories: 260.9,
    serving_size_g: 100,
    fat_total_g: 22,
    fat_saturated_g: 13.7,
    protein_g: 3.1,
    sodium_mg: 8,
    potassium_mg: 87,
    cholesterol_mg: 77,
    carbohydrates_total_g: 12.7,
    fiber_g: 0,
    sugar_g: 8.1,
  },
  {
    name: 'fromage à la crème',
    category: 4,
    calories: 342,
    serving_size_g: 100,
    fat_total_g: 34,
    fat_saturated_g: 20.1,
    protein_g: 6.2,
    sodium_mg: 309,
    potassium_mg: 106,
    cholesterol_mg: 100,
    carbohydrates_total_g: 5.5,
    fiber_g: 0,
    sugar_g: 3.7,
  },
  {
    name: 'mascarpone',
    category: 4,
    calories: 444.5,
    serving_size_g: 100,
    fat_total_g: 45.6,
    fat_saturated_g: 27.3,
    protein_g: 4.6,
    sodium_mg: 431,
    potassium_mg: 84,
    cholesterol_mg: 134,
    carbohydrates_total_g: 3,
    fiber_g: 0,
    sugar_g: 2.4,
  },
  {
    name: 'beurre',
    category: 4,
    calories: 721.5,
    serving_size_g: 100,
    fat_total_g: 79.6,
    fat_saturated_g: 51.1,
    protein_g: 0.8,
    sodium_mg: 637,
    potassium_mg: 23,
    cholesterol_mg: 215,
    carbohydrates_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 0.1,
  },
  {
    name: 'crème aigre',
    category: 4,
    calories: 192.5,
    serving_size_g: 100,
    fat_total_g: 19.6,
    fat_saturated_g: 10.1,
    protein_g: 2.4,
    sodium_mg: 30,
    potassium_mg: 76,
    cholesterol_mg: 58,
    carbohydrates_total_g: 4.7,
    fiber_g: 0,
    sugar_g: 3.4,
  },
  {
    name: 'brie',
    category: 4,
    calories: 326.3,
    serving_size_g: 100,
    fat_total_g: 27.2,
    fat_saturated_g: 17.5,
    protein_g: 20.8,
    sodium_mg: 633,
    potassium_mg: 191,
    cholesterol_mg: 99,
    carbohydrates_total_g: 0.5,
    fiber_g: 0,
    sugar_g: 0.5,
  },
  {
    name: 'orge',
    category: 4,
    calories: 124.8,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 2.2,
    sodium_mg: 3,
    potassium_mg: 54,
    cholesterol_mg: 0,
    carbohydrates_total_g: 28.6,
    fiber_g: 3.9,
    sugar_g: 0.3,
  },
  {
    name: 'polenta',
    category: 5,
    calories: 79.6,
    serving_size_g: 100,
    fat_total_g: 4.6,
    fat_saturated_g: 2.6,
    protein_g: 2.1,
    sodium_mg: 301,
    potassium_mg: 53,
    cholesterol_mg: 11,
    carbohydrates_total_g: 8.7,
    fiber_g: 0.8,
    sugar_g: 0.1,
  },
  {
    name: 'couscous',
    category: 5,
    calories: 114.1,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 3.8,
    sodium_mg: 5,
    potassium_mg: 22,
    cholesterol_mg: 0,
    carbohydrates_total_g: 23.4,
    fiber_g: 1.4,
    sugar_g: 0.1,
  },
  {
    name: 'croissants',
    category: 5,
    calories: 416.8,
    serving_size_g: 100,
    fat_total_g: 21.3,
    fat_saturated_g: 11.6,
    protein_g: 8.3,
    sodium_mg: 458,
    potassium_mg: 103,
    cholesterol_mg: 66,
    carbohydrates_total_g: 46.7,
    fiber_g: 2.6,
    sugar_g: 11.2,
  },
  {
    name: 'bagels',
    category: 5,
    calories: 265.4,
    serving_size_g: 100,
    fat_total_g: 1.3,
    fat_saturated_g: 0.4,
    protein_g: 10.5,
    sodium_mg: 428,
    potassium_mg: 100,
    cholesterol_mg: 0,
    carbohydrates_total_g: 51.9,
    fiber_g: 1.6,
    sugar_g: 8.4,
  },
  {
    name: 'tortillas',
    category: 5,
    calories: 327.3,
    serving_size_g: 100,
    fat_total_g: 7.2,
    fat_saturated_g: 1.7,
    protein_g: 8.6,
    sodium_mg: 474,
    potassium_mg: 125,
    cholesterol_mg: 0,
    carbohydrates_total_g: 55.7,
    fiber_g: 3.4,
    sugar_g: 0,
  },
  {
    name: 'pâtes',
    category: 5,
    calories: 156,
    serving_size_g: 100,
    fat_total_g: 0.9,
    fat_saturated_g: 0.2,
    protein_g: 5.7,
    sodium_mg: 1,
    potassium_mg: 58,
    cholesterol_mg: 0,
    carbohydrates_total_g: 31.3,
    fiber_g: 1.8,
    sugar_g: 0.6,
  },
  {
    name: 'sarrasin',
    category: 5,
    calories: 92.5,
    serving_size_g: 100,
    fat_total_g: 0.6,
    fat_saturated_g: 0.1,
    protein_g: 3.4,
    sodium_mg: 3,
    potassium_mg: 70,
    cholesterol_mg: 0,
    carbohydrates_total_g: 20.1,
    fiber_g: 2.7,
    sugar_g: 0.9,
  },
  {
    name: 'pain',
    category: 5,
    calories: 261.6,
    serving_size_g: 100,
    fat_total_g: 3.4,
    fat_saturated_g: 0.7,
    protein_g: 8.8,
    sodium_mg: 495,
    potassium_mg: 98,
    cholesterol_mg: 0,
    carbohydrates_total_g: 50.2,
    fiber_g: 2.7,
    sugar_g: 5.7,
  },
  {
    name: 'naan',
    category: 5,
    calories: 284.4,
    serving_size_g: 100,
    fat_total_g: 5.6,
    fat_saturated_g: 1.4,
    protein_g: 9.6,
    sodium_mg: 463,
    potassium_mg: 100,
    cholesterol_mg: 0,
    carbohydrates_total_g: 51.2,
    fiber_g: 2.2,
    sugar_g: 3.5,
  },
  {
    name: 'quinoa',
    category: 5,
    calories: 121.8,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 0.2,
    protein_g: 4.4,
    sodium_mg: 6,
    potassium_mg: 152,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21,
    fiber_g: 2.8,
    sugar_g: 0.9,
  },
  {
    name: 'chapelure',
    category: 5,
    calories: 399.9,
    serving_size_g: 100,
    fat_total_g: 5.4,
    fat_saturated_g: 1.2,
    protein_g: 13.3,
    sodium_mg: 717,
    potassium_mg: 166,
    cholesterol_mg: 0,
    carbohydrates_total_g: 71.4,
    fiber_g: 4.5,
    sugar_g: 6.2,
  },
  {
    name: 'farine',
    category: 5,
    calories: 362.6,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0.2,
    protein_g: 10.2,
    sodium_mg: 2,
    potassium_mg: 106,
    cholesterol_mg: 0,
    carbohydrates_total_g: 77,
    fiber_g: 2.7,
    sugar_g: 0.3,
  },
  {
    name: 'granola',
    category: 5,
    calories: 475.7,
    serving_size_g: 100,
    fat_total_g: 23.9,
    fat_saturated_g: 4,
    protein_g: 13.6,
    sodium_mg: 25,
    potassium_mg: 432,
    cholesterol_mg: 0,
    carbohydrates_total_g: 54.3,
    fiber_g: 9,
    sugar_g: 20,
  },
  {
    name: 'riz',
    category: 5,
    calories: 127.4,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    protein_g: 2.7,
    sodium_mg: 1,
    potassium_mg: 42,
    cholesterol_mg: 0,
    carbohydrates_total_g: 28.4,
    fiber_g: 0.4,
    sugar_g: 0.1,
  },
  {
    name: 'avoine',
    category: 5,
    calories: 386.8,
    serving_size_g: 100,
    fat_total_g: 6.6,
    fat_saturated_g: 1.1,
    protein_g: 13.3,
    sodium_mg: 5,
    potassium_mg: 417,
    cholesterol_mg: 0,
    carbohydrates_total_g: 68,
    fiber_g: 10.2,
    sugar_g: 1,
  },
  {
    name: 'bretzels',
    category: 5,
    calories: 389.1,
    serving_size_g: 100,
    fat_total_g: 2.9,
    fat_saturated_g: 0.4,
    protein_g: 10.1,
    sodium_mg: 1216,
    potassium_mg: 127,
    cholesterol_mg: 0,
    carbohydrates_total_g: 81.2,
    fiber_g: 3.4,
    sugar_g: 2.2,
  },
  {
    name: 'croûtons',
    category: 5,
    calories: 459.5,
    serving_size_g: 100,
    fat_total_g: 18.3,
    fat_saturated_g: 5.3,
    protein_g: 10.7,
    sodium_mg: 1089,
    potassium_mg: 139,
    cholesterol_mg: 6,
    carbohydrates_total_g: 64.7,
    fiber_g: 4.9,
    sugar_g: 4.5,
  },
  {
    name: 'céréales',
    category: 5,
    calories: 386,
    serving_size_g: 100,
    fat_total_g: 6.8,
    fat_saturated_g: 1.5,
    protein_g: 12.2,
    sodium_mg: 495,
    potassium_mg: 489,
    cholesterol_mg: 0,
    carbohydrates_total_g: 71.9,
    fiber_g: 9.2,
    sugar_g: 4.3,
  },
  {
    name: 'semoule de maïs',
    category: 5,
    calories: 368.6,
    serving_size_g: 100,
    fat_total_g: 3.5,
    fat_saturated_g: 0.5,
    protein_g: 8.1,
    sodium_mg: 34,
    potassium_mg: 237,
    cholesterol_mg: 0,
    carbohydrates_total_g: 76.1,
    fiber_g: 7.3,
    sugar_g: 0.6,
  },
  {
    name: 'noix de cajou',
    category: 6,
    calories: 558.6,
    serving_size_g: 100,
    fat_total_g: 46.1,
    fat_saturated_g: 9,
    protein_g: 15.2,
    sodium_mg: 631,
    potassium_mg: 494,
    cholesterol_mg: 0,
    carbohydrates_total_g: 32.2,
    fiber_g: 3.1,
    sugar_g: 5.1,
  },
  {
    name: 'amandes',
    category: 6,
    calories: 603.7,
    serving_size_g: 100,
    fat_total_g: 52.7,
    fat_saturated_g: 3.9,
    protein_g: 21,
    sodium_mg: 490,
    potassium_mg: 466,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21.3,
    fiber_g: 11.1,
    sugar_g: 4.6,
  },
  {
    name: 'noix du Brésil',
    category: 6,
    calories: 669.9,
    serving_size_g: 100,
    fat_total_g: 66.5,
    fat_saturated_g: 16.1,
    protein_g: 14.4,
    sodium_mg: 3,
    potassium_mg: 712,
    cholesterol_mg: 0,
    carbohydrates_total_g: 11.8,
    fiber_g: 7.6,
    sugar_g: 2.4,
  },
  {
    name: 'cacahuètes',
    category: 6,
    calories: 600.9,
    serving_size_g: 100,
    fat_total_g: 49.9,
    fat_saturated_g: 8.1,
    protein_g: 24.1,
    sodium_mg: 415,
    potassium_mg: 356,
    cholesterol_mg: 0,
    carbohydrates_total_g: 20.8,
    fiber_g: 8.1,
    sugar_g: 5,
  },
  {
    name: 'pistaches',
    category: 6,
    calories: 584,
    serving_size_g: 100,
    fat_total_g: 44.9,
    fat_saturated_g: 5.7,
    protein_g: 21.5,
    sodium_mg: 432,
    potassium_mg: 471,
    cholesterol_mg: 0,
    carbohydrates_total_g: 27.2,
    fiber_g: 10,
    sugar_g: 7.1,
  },
  {
    name: 'graines de sésame',
    category: 6,
    calories: 575.8,
    serving_size_g: 100,
    fat_total_g: 49,
    fat_saturated_g: 6.8,
    protein_g: 17,
    sodium_mg: 11,
    potassium_mg: 629,
    cholesterol_mg: 0,
    carbohydrates_total_g: 26.2,
    fiber_g: 14,
    sugar_g: 0,
  },
  {
    name: 'graines de chia',
    category: 6,
    calories: 475.3,
    serving_size_g: 100,
    fat_total_g: 30.9,
    fat_saturated_g: 3.4,
    protein_g: 16.6,
    sodium_mg: 15,
    potassium_mg: 859,
    cholesterol_mg: 0,
    carbohydrates_total_g: 42.3,
    fiber_g: 34,
    sugar_g: 0,
  },
  {
    name: 'noisettes',
    category: 6,
    calories: 662.2,
    serving_size_g: 100,
    fat_total_g: 62.8,
    fat_saturated_g: 4.5,
    protein_g: 14.9,
    sodium_mg: 0,
    potassium_mg: 307,
    cholesterol_mg: 0,
    carbohydrates_total_g: 17.7,
    fiber_g: 9.2,
    sugar_g: 4.9,
  },
  {
    name: 'noix de pécan',
    category: 6,
    calories: 711.9,
    serving_size_g: 100,
    fat_total_g: 71.6,
    fat_saturated_g: 6,
    protein_g: 9.4,
    sodium_mg: 0,
    potassium_mg: 279,
    cholesterol_mg: 0,
    carbohydrates_total_g: 14.1,
    fiber_g: 9.5,
    sugar_g: 4,
  },
  {
    name: 'flocons de noix de coco',
    category: 6,
    calories: 728.5,
    serving_size_g: 100,
    fat_total_g: 76.6,
    fat_saturated_g: 12.1,
    protein_g: 7.8,
    sodium_mg: 5,
    potassium_mg: 186,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.8,
    fiber_g: 8.8,
    sugar_g: 4.6,
  },
  {
    name: 'graines de pavot',
    category: 6,
    calories: 461.9,
    serving_size_g: 100,
    fat_total_g: 27.9,
    fat_saturated_g: 26.1,
    protein_g: 3.1,
    sodium_mg: 289,
    potassium_mg: 101,
    cholesterol_mg: 0,
    carbohydrates_total_g: 50.9,
    fiber_g: 9.7,
    sugar_g: 36.6,
  },
  {
    name: 'quinoa',
    category: 6,
    calories: 534.4,
    serving_size_g: 100,
    fat_total_g: 40.7,
    fat_saturated_g: 4.7,
    protein_g: 18,
    sodium_mg: 26,
    potassium_mg: 861,
    cholesterol_mg: 0,
    carbohydrates_total_g: 28.2,
    fiber_g: 19.3,
    sugar_g: 2.9,
  },
  {
    name: 'coquelicot',
    category: 6,
    calories: 121.8,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 0.2,
    protein_g: 4.4,
    sodium_mg: 6,
    potassium_mg: 152,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21,
    fiber_g: 2.8,
    sugar_g: 0.9,
  },
  {
    name: 'tahini',
    category: 6,
    calories: 590.1,
    serving_size_g: 100,
    fat_total_g: 54,
    fat_saturated_g: 7.5,
    protein_g: 17.3,
    sodium_mg: 35,
    potassium_mg: 789,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21.2,
    fiber_g: 4.8,
    sugar_g: 0,
  },
  {
    name: 'châtaignes',
    category: 6,
    calories: 252.2,
    serving_size_g: 100,
    fat_total_g: 2.2,
    fat_saturated_g: 0.4,
    protein_g: 3.2,
    sodium_mg: 2,
    potassium_mg: 107,
    cholesterol_mg: 0,
    carbohydrates_total_g: 53,
    fiber_g: 5.2,
    sugar_g: 10.6,
  },
  {
    name: 'graines de tournesol',
    category: 6,
    calories: 554.7,
    serving_size_g: 100,
    fat_total_g: 50.7,
    fat_saturated_g: 5.2,
    protein_g: 19.4,
    sodium_mg: 5910,
    potassium_mg: 1162,
    cholesterol_mg: 0,
    carbohydrates_total_g: 15.5,
    fiber_g: 8.8,
    sugar_g: 2.7,
  },
  {
    name: 'graines de chanvre',
    category: 6,
    calories: 565.8,
    serving_size_g: 100,
    fat_total_g: 48.4,
    fat_saturated_g: 4.6,
    protein_g: 31.3,
    sodium_mg: 4,
    potassium_mg: 1680,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.5,
    fiber_g: 4,
    sugar_g: 1.5,
  },
  {
    name: 'graines de citrouille',
    category: 6,
    calories: 436,
    serving_size_g: 100,
    fat_total_g: 19.5,
    fat_saturated_g: 3.7,
    protein_g: 18.6,
    sodium_mg: 17,
    potassium_mg: 91,
    cholesterol_mg: 0,
    carbohydrates_total_g: 53.5,
    fiber_g: 18.3,
    sugar_g: 0,
  },
  {
    name: 'noix',
    category: 6,
    calories: 664.8,
    serving_size_g: 100,
    fat_total_g: 64.5,
    fat_saturated_g: 5.9,
    protein_g: 15.2,
    sodium_mg: 2,
    potassium_mg: 350,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.6,
    fiber_g: 6.9,
    sugar_g: 2.4,
  },
  {
    name: 'origan',
    category: 6,
    calories: 269,
    serving_size_g: 100,
    fat_total_g: 4,
    fat_saturated_g: 2,
    protein_g: 9,
    sodium_mg: 25,
    potassium_mg: 147,
    cholesterol_mg: 0,
    carbohydrates_total_g: 69.1,
    fiber_g: 42.2,
    sugar_g: 4,
  },
  {
    name: 'coriandre',
    category: 7,
    calories: 22.9,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0,
    protein_g: 2.3,
    sodium_mg: 45,
    potassium_mg: 48,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.8,
    fiber_g: 2.8,
    sugar_g: 0.8,
  },
  {
    name: 'thym',
    calories: 102.7,
    category: 7,
    serving_size_g: 100,
    fat_total_g: 1.2,
    fat_saturated_g: 0,
    protein_g: 5,
    sodium_mg: 8,
    potassium_mg: 106,
    cholesterol_mg: 0,
    carbohydrates_total_g: 25.1,
    fiber_g: 13.6,
    sugar_g: 0,
  },
  {
    name: 'cannelle',
    calories: 247.4,
    category: 7,

    serving_size_g: 100,
    fat_total_g: 1.1,
    fat_saturated_g: 0.4,
    protein_g: 3.9,
    sodium_mg: 10,
    potassium_mg: 64,
    cholesterol_mg: 0,
    carbohydrates_total_g: 80.4,
    fiber_g: 53.8,
    sugar_g: 2.3,
  },
  {
    name: 'cardamome',
    category: 7,
    calories: 314.5,
    serving_size_g: 100,
    fat_total_g: 6.4,
    fat_saturated_g: 0.5,
    protein_g: 10.9,
    sodium_mg: 18,
    potassium_mg: 177,
    cholesterol_mg: 0,
    carbohydrates_total_g: 68.3,
    fiber_g: 27.9,
    sugar_g: 0,
  },
  {
    name: 'curcuma',
    category: 7,
    calories: 309.4,
    serving_size_g: 100,
    fat_total_g: 3.4,
    fat_saturated_g: 2,
    protein_g: 9.6,
    sodium_mg: 26,
    potassium_mg: 299,
    cholesterol_mg: 0,
    carbohydrates_total_g: 68,
    fiber_g: 22.6,
    sugar_g: 3.4,
  },
  {
    name: 'ciboulette',
    category: 7,
    calories: 30,
    serving_size_g: 100,
    fat_total_g: 0.7,
    fat_saturated_g: 0,
    protein_g: 3.4,
    sodium_mg: 2,
    potassium_mg: 57,
    cholesterol_mg: 0,
    carbohydrates_total_g: 4.3,
    fiber_g: 2.7,
    sugar_g: 2,
  },
  {
    name: 'romarin',
    category: 7,
    calories: 335.6,
    serving_size_g: 100,
    fat_total_g: 14.8,
    fat_saturated_g: 7.5,
    protein_g: 5,
    sodium_mg: 50,
    potassium_mg: 69,
    cholesterol_mg: 0,
    carbohydrates_total_g: 64.1,
    fiber_g: 42,
    sugar_g: 0,
  },
  {
    name: 'aneth',
    category: 7,
    calories: 44.3,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0,
    protein_g: 3,
    sodium_mg: 61,
    potassium_mg: 66,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.1,
    fiber_g: 2,
    sugar_g: 0,
  },
  {
    name: 'gingembre',
    category: 7,
    calories: 78.3,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0,
    protein_g: 2,
    sodium_mg: 13,
    potassium_mg: 34,
    cholesterol_mg: 0,
    carbohydrates_total_g: 18.3,
    fiber_g: 2,
    sugar_g: 1.5,
  },
  {
    name: 'cumin',
    category: 7,
    calories: 379.3,
    serving_size_g: 100,
    fat_total_g: 22.4,
    fat_saturated_g: 1.4,
    protein_g: 17.8,
    sodium_mg: 170,
    potassium_mg: 500,
    cholesterol_mg: 0,
    carbohydrates_total_g: 44.5,
    fiber_g: 10.5,
    sugar_g: 2.4,
  },
  {
    name: 'basilic',
    category: 7,
    calories: 24.4,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 4,
    sodium_mg: 4,
    potassium_mg: 56,
    cholesterol_mg: 0,
    carbohydrates_total_g: 2,
    fiber_g: 2,
    sugar_g: 0,
  },
  {
    name: 'laurier',
    category: 7,
    calories: 320.3,
    serving_size_g: 100,
    fat_total_g: 10.1,
    fat_saturated_g: 0,
    protein_g: 10.1,
    sodium_mg: 24,
    potassium_mg: 116,
    cholesterol_mg: 0,
    carbohydrates_total_g: 75.6,
    fiber_g: 24.5,
    sugar_g: 0,
  },
  {
    name: 'anis',
    category: 7,
    calories: 328.1,
    serving_size_g: 100,
    fat_total_g: 15.5,
    fat_saturated_g: 0.5,
    protein_g: 17.6,
    sodium_mg: 16,
    potassium_mg: 440,
    cholesterol_mg: 0,
    carbohydrates_total_g: 49.3,
    fiber_g: 14.5,
    sugar_g: 0,
  },
  {
    name: 'coriandre',
    category: 7,
    calories: 306.3,
    serving_size_g: 100,
    fat_total_g: 17.8,
    fat_saturated_g: 1.1,
    protein_g: 12.3,
    sodium_mg: 34,
    potassium_mg: 405,
    cholesterol_mg: 0,
    carbohydrates_total_g: 55.2,
    fiber_g: 41,
    sugar_g: 0,
  },
  {
    name: 'fenouil',
    category: 7,
    calories: 30.7,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    protein_g: 1.2,
    sodium_mg: 51,
    potassium_mg: 49,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.3,
    fiber_g: 3.1,
    sugar_g: 3.9,
  },
  {
    name: 'menthe',
    category: 7,
    calories: 405.2,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 38,
    potassium_mg: 2,
    cholesterol_mg: 0,
    carbohydrates_total_g: 98.6,
    fiber_g: 0,
    sugar_g: 63.5,
  },
  {
    name: 'sauge',
    category: 7,
    calories: 313.2,
    serving_size_g: 100,
    fat_total_g: 13.1,
    fat_saturated_g: 7.1,
    protein_g: 10.1,
    sodium_mg: 11,
    potassium_mg: 91,
    cholesterol_mg: 0,
    carbohydrates_total_g: 60.5,
    fiber_g: 39.9,
    sugar_g: 1.4,
  },
  {
    name: 'persil',
    category: 7,
    calories: 36.1,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.3,
    protein_g: 2.9,
    sodium_mg: 56,
    potassium_mg: 58,
    cholesterol_mg: 0,
    carbohydrates_total_g: 6.2,
    fiber_g: 3.5,
    sugar_g: 0.8,
  },
  {
    name: 'safran',
    category: 7,
    calories: 301.8,
    serving_size_g: 100,
    fat_total_g: 5.8,
    fat_saturated_g: 1.4,
    protein_g: 11.5,
    sodium_mg: 145,
    potassium_mg: 248,
    cholesterol_mg: 0,
    carbohydrates_total_g: 65.5,
    fiber_g: 4.3,
    sugar_g: 0,
  },
  {
    name: 'poivre',
    category: 7,
    calories: 248.5,
    serving_size_g: 100,
    fat_total_g: 3,
    fat_saturated_g: 1.3,
    protein_g: 10.5,
    sodium_mg: 19,
    potassium_mg: 160,
    cholesterol_mg: 0,
    carbohydrates_total_g: 63.1,
    fiber_g: 25.4,
    sugar_g: 0.4,
  },
  {
    name: 'salsa',
    category: 8,
    calories: 29.6,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 1.5,
    sodium_mg: 715,
    potassium_mg: 32,
    cholesterol_mg: 0,
    carbohydrates_total_g: 6.5,
    fiber_g: 1.9,
    sugar_g: 4,
  },
  {
    name: "sirop d'érable",
    category: 8,
    calories: 267.5,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 11,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 67.8,
    fiber_g: 0,
    sugar_g: 59.9,
  },
  {
    name: 'sauce worcestershire',
    category: 8,
    calories: 76.8,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 972,
    potassium_mg: 60,
    cholesterol_mg: 0,
    carbohydrates_total_g: 19.7,
    fiber_g: 0,
    sugar_g: 10.1,
  },
  {
    name: 'sauce bbq',
    category: 8,
    calories: 166.9,
    serving_size_g: 100,
    fat_total_g: 0.6,
    fat_saturated_g: 0.1,
    protein_g: 0.8,
    sodium_mg: 1021,
    potassium_mg: 19,
    cholesterol_mg: 0,
    carbohydrates_total_g: 40.1,
    fiber_g: 0.9,
    sugar_g: 33.5,
  },
  {
    name: 'huile végétale',
    category: 8,
    calories: 877.4,
    serving_size_g: 100,
    fat_total_g: 98.7,
    fat_saturated_g: 7.4,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'pesto',
    category: 8,
    calories: 502.4,
    serving_size_g: 100,
    fat_total_g: 49.1,
    fat_saturated_g: 9.1,
    protein_g: 11.1,
    sodium_mg: 490,
    potassium_mg: 288,
    cholesterol_mg: 23,
    carbohydrates_total_g: 7.5,
    fiber_g: 1.1,
    sugar_g: 0.8,
  },
  {
    name: 'sauce soja',
    category: 8,
    calories: 53,
    serving_size_g: 100,
    fat_total_g: 0.6,
    fat_saturated_g: 0.1,
    protein_g: 8.1,
    sodium_mg: 5415,
    potassium_mg: 167,
    cholesterol_mg: 0,
    carbohydrates_total_g: 4.8,
    fiber_g: 0.8,
    sugar_g: 0.4,
  },
  {
    name: 'vinaigre',
    category: 8,
    calories: 18.1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 2,
    potassium_mg: 4,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 0.1,
  },
  {
    name: 'moutarde',
    category: 8,
    calories: 58.3,
    serving_size_g: 100,
    fat_total_g: 3.4,
    fat_saturated_g: 0.2,
    protein_g: 3.8,
    sodium_mg: 1125,
    potassium_mg: 106,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.7,
    fiber_g: 4,
    sugar_g: 1,
  },
  {
    name: 'miel',
    category: 8,
    calories: 302.9,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.3,
    sodium_mg: 3,
    potassium_mg: 3,
    cholesterol_mg: 0,
    carbohydrates_total_g: 83,
    fiber_g: 0.2,
    sugar_g: 82.6,
  },
  {
    name: 'ketchup',
    category: 8,
    calories: 100.7,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 1.1,
    sodium_mg: 890,
    potassium_mg: 25,
    cholesterol_mg: 0,
    carbohydrates_total_g: 27.6,
    fiber_g: 0.3,
    sugar_g: 21.3,
  },
  {
    name: 'huile de sésame',
    category: 8,
    calories: 858.8,
    serving_size_g: 100,
    fat_total_g: 100.6,
    fat_saturated_g: 14.1,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: "huile d'olive",
    category: 8,
    calories: 869.2,
    serving_size_g: 100,
    fat_total_g: 101.2,
    fat_saturated_g: 13.9,
    protein_g: 0,
    sodium_mg: 1,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'huile de tournesol',
    category: 8,
    calories: 870.1,
    serving_size_g: 100,
    fat_total_g: 99.5,
    fat_saturated_g: 9.8,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'sauce piquante',
    category: 8,
    calories: 11.1,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0,
    protein_g: 0.4,
    sodium_mg: 2652,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 1.7,
    fiber_g: 0.2,
    sugar_g: 1.3,
  },
  {
    name: 'sauce de poisson',
    category: 8,
    calories: 34.5,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 5.1,
    sodium_mg: 7785,
    potassium_mg: 7,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.6,
    fiber_g: 0,
    sugar_g: 3.6,
  },
  {
    name: "huile d'arachide",
    category: 8,
    calories: 883,
    serving_size_g: 100,
    fat_total_g: 98.9,
    fat_saturated_g: 16.9,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'mayonnaise',
    category: 8,
    calories: 689.3,
    serving_size_g: 100,
    fat_total_g: 74.7,
    fat_saturated_g: 11.8,
    protein_g: 0.9,
    sodium_mg: 626,
    potassium_mg: 20,
    cholesterol_mg: 41,
    carbohydrates_total_g: 0.6,
    fiber_g: 0,
    sugar_g: 0.6,
  },
  {
    name: 'huile de coco',
    category: 8,
    calories: 881.6,
    serving_size_g: 100,
    fat_total_g: 98.8,
    fat_saturated_g: 83.1,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'huile de canola',
    category: 8,
    calories: 886.3,
    serving_size_g: 100,
    fat_total_g: 98.2,
    fat_saturated_g: 7.3,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'extrait de vanille',
    category: 9,
    calories: 292.9,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 9,
    potassium_mg: 6,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12.7,
    fiber_g: 0,
    sugar_g: 12.7,
  },
  {
    name: 'sucre en poudre',
    category: 9,
    calories: 391.1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 2,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 98.1,
    fiber_g: 0,
    sugar_g: 97.1,
  },
  {
    name: "extrait d'amande",
    category: 9,
    calories: 292.9,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 8,
    potassium_mg: 5,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12.8,
    fiber_g: 0,
    sugar_g: 12.7,
  },
  {
    name: 'miel',
    category: 9,
    calories: 302.9,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.3,
    sodium_mg: 3,
    potassium_mg: 3,
    cholesterol_mg: 0,
    carbohydrates_total_g: 83,
    fiber_g: 0.2,
    sugar_g: 82.6,
  },
  {
    name: 'sucre',
    category: 9,
    calories: 385.6,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 99.8,
    fiber_g: 0,
    sugar_g: 100.1,
  },
  {
    name: 'levure',
    category: 9,
    calories: 321.7,
    serving_size_g: 100,
    fat_total_g: 7.5,
    fat_saturated_g: 1,
    protein_g: 40.4,
    sodium_mg: 50,
    potassium_mg: 634,
    cholesterol_mg: 0,
    carbohydrates_total_g: 41.9,
    fiber_g: 26.5,
    sugar_g: 0,
  },
  {
    name: 'mélange à crêpes',
    category: 9,
    calories: 364.5,
    serving_size_g: 100,
    fat_total_g: 3.1,
    fat_saturated_g: 0.8,
    protein_g: 9.8,
    sodium_mg: 1083,
    potassium_mg: 610,
    cholesterol_mg: 2,
    carbohydrates_total_g: 74.8,
    fiber_g: 2.9,
    sugar_g: 15.9,
  },
  {
    name: 'mélange pour gâteaux',
    category: 9,
    calories: 364.7,
    serving_size_g: 100,
    fat_total_g: 3.5,
    fat_saturated_g: 1.6,
    protein_g: 3.7,
    sodium_mg: 738,
    potassium_mg: 308,
    cholesterol_mg: 0,
    carbohydrates_total_g: 83.5,
    fiber_g: 1.2,
    sugar_g: 43.5,
  },
  {
    name: 'sucre roux',
    category: 9,
    calories: 381.1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 27,
    potassium_mg: 3,
    cholesterol_mg: 0,
    carbohydrates_total_g: 98.8,
    fiber_g: 0,
    sugar_g: 97.8,
  },
  {
    name: 'fécule de maïs',
    category: 9,
    calories: 386.4,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.3,
    sodium_mg: 9,
    potassium_mg: 13,
    cholesterol_mg: 0,
    carbohydrates_total_g: 89.9,
    fiber_g: 0.9,
    sugar_g: 0,
  },
  {
    name: 'farine',
    category: 9,
    calories: 362.6,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0.2,
    protein_g: 10.2,
    sodium_mg: 2,
    potassium_mg: 106,
    cholesterol_mg: 0,
    carbohydrates_total_g: 77,
    fiber_g: 2.7,
    sugar_g: 0.3,
  },
  {
    name: 'poudre de cacao',
    category: 9,
    calories: 410,
    serving_size_g: 100,
    fat_total_g: 9.9,
    fat_saturated_g: 0,
    protein_g: 20,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 58.8,
    fiber_g: 20.1,
    sugar_g: 0,
  },
  {
    name: "nectar d'agave",
    category: 9,
    calories: 313.1,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 4,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 76.3,
    fiber_g: 0.1,
    sugar_g: 67.6,
  },
  {
    name: 'saupoudrage',
    category: 9,
    calories: 534.4,
    serving_size_g: 100,
    fat_total_g: 28.4,
    fat_saturated_g: 2,
    protein_g: 0,
    sodium_mg: 2,
    potassium_mg: 2,
    cholesterol_mg: 0,
    carbohydrates_total_g: 69.7,
    fiber_g: 0.2,
    sugar_g: 51.6,
  },
  {
    name: 'mélasse',
    category: 9,
    calories: 287.4,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 36,
    potassium_mg: 30,
    cholesterol_mg: 0,
    carbohydrates_total_g: 75.9,
    fiber_g: 0,
    sugar_g: 74.4,
  },
  {
    name: 'bicarbonate de soude',
    category: 9,
    calories: 0,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 27579,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: "sirop d'érable",
    category: 9,
    calories: 267.5,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 11,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 67.8,
    fiber_g: 0,
    sugar_g: 59.9,
  },
  {
    name: 'poudre à lever',
    category: 9,
    calories: 54.1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 10622,
    potassium_mg: 2156,
    cholesterol_mg: 0,
    carbohydrates_total_g: 27.5,
    fiber_g: 0.2,
    sugar_g: 0,
  },
  {
    name: 'jus de fruit',
    category: 10,
    calories: 53.7,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 61,
    potassium_mg: 6,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.3,
    fiber_g: 0.1,
    sugar_g: 12.2,
  },
  {
    name: 'cocktail',
    category: 10,
    calories: 139.7,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    protein_g: 0.2,
    sodium_mg: 1,
    potassium_mg: 8,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.7,
    fiber_g: 0.1,
    sugar_g: 8.4,
  },
  {
    name: 'chaï',
    category: 10,
    calories: 2,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0.6,
    fiber_g: 0.1,
    sugar_g: 0,
  },
  {
    name: 'smoothie',
    category: 10,
    calories: 79.7,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.5,
    protein_g: 2.7,
    sodium_mg: 29,
    potassium_mg: 71,
    cholesterol_mg: 2,
    carbohydrates_total_g: 16.7,
    fiber_g: 1.4,
    sugar_g: 11.7,
  },
  {
    name: 'lait de coco',
    category: 10,
    calories: 197.2,
    serving_size_g: 100,
    fat_total_g: 21.2,
    fat_saturated_g: 18.8,
    protein_g: 2,
    sodium_mg: 12,
    potassium_mg: 97,
    cholesterol_mg: 0,
    carbohydrates_total_g: 2.8,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'soda',
    category: 10,
    calories: 41.9,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 2,
    potassium_mg: 8,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.2,
    fiber_g: 0,
    sugar_g: 10,
  },
  {
    name: 'thé',
    category: 10,
    calories: 1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0.3,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'lait',
    category: 10,
    calories: 51.3,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 1.2,
    protein_g: 3.5,
    sodium_mg: 52,
    potassium_mg: 100,
    cholesterol_mg: 8,
    carbohydrates_total_g: 4.9,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    category: 10,
    name: 'café',
    calories: 1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 1,
    potassium_mg: 2,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'thé glacé',
    category: 10,
    calories: 1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 3,
    potassium_mg: 1,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0.3,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'vin',
    category: 10,
    calories: 81.4,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 2.6,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'bière',
    category: 10,
    calories: 43.3,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.5,
    sodium_mg: 3,
    potassium_mg: 13,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.6,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'protéine en poudre',
    category: 10,
    calories: 348.4,
    serving_size_g: 100,
    fat_total_g: 1.5,
    fat_saturated_g: 0.8,
    protein_g: 77.9,
    sodium_mg: 158,
    potassium_mg: 1310,
    cholesterol_mg: 16,
    carbohydrates_total_g: 6.2,
    fiber_g: 3.1,
    sugar_g: 0,
  },
  {
    name: 'lait de soja',
    category: 10,
    calories: 40.9,
    serving_size_g: 100,
    fat_total_g: 1.7,
    fat_saturated_g: 0.2,
    protein_g: 2.9,
    sodium_mg: 49,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.3,
    fiber_g: 0.4,
    sugar_g: 2.5,
  },
  {
    name: 'eau',
    category: 10,
    calories: 0,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 4,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'eau de Seltz',
    category: 10,
    calories: 0,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
  },
  {
    name: 'limonade',
    category: 10,
    calories: 38.9,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.1,
    sodium_mg: 3,
    potassium_mg: 2,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.6,
    fiber_g: 0,
    sugar_g: 10,
  },
  {
    name: "lait d'amande",
    category: 10,
    calories: 22,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0.1,
    protein_g: 0.4,
    sodium_mg: 3,
    potassium_mg: 9,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.2,
    fiber_g: 0.3,
    sugar_g: 2.9,
  },
  {
    name: 'boissons énergétiques',
    category: 10,
    calories: 43.4,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    protein_g: 0.5,
    sodium_mg: 39,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.4,
    fiber_g: 0,
    sugar_g: 10.1,
  },
  {
    name: 'chocolat chaud',
    category: 10,
    calories: 54.2,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0.3,
    protein_g: 0.9,
    sodium_mg: 72,
    potassium_mg: 42,
    cholesterol_mg: 0,
    carbohydrates_total_g: 11.4,
    fiber_g: 0.5,
    sugar_g: 9,
  },
];


module.exports = finals