[
  {
    name: "eggplants",
    calories: 35.5,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.8,
    sodium_mg: 0,
    potassium_mg: 15,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.9,
    fiber_g: 2.5,
    sugar_g: 3.2,
  },
  {
    name: "fish fillets",
    calories: 106.2,
    serving_size_g: 100.0,
    fat_total_g: 0.9,
    fat_saturated_g: 0.2,
    protein_g: 23.6,
    sodium_mg: 112,
    potassium_mg: 181,
    cholesterol_mg: 94,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "oranges",
    calories: 49.8,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 0.9,
    sodium_mg: 1,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12.5,
    fiber_g: 2.2,
    sugar_g: 8.6,
  },
  {
    name: "lobster",
    calories: 143.7,
    serving_size_g: 100.0,
    fat_total_g: 1.9,
    fat_saturated_g: 0.3,
    protein_g: 26.5,
    sodium_mg: 224,
    potassium_mg: 229,
    cholesterol_mg: 89,
    carbohydrates_total_g: 3.1,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "cottage cheese",
    calories: 98.3,
    serving_size_g: 100.0,
    fat_total_g: 4.3,
    fat_saturated_g: 1.7,
    protein_g: 11.2,
    sodium_mg: 370,
    potassium_mg: 161,
    cholesterol_mg: 16,
    carbohydrates_total_g: 3.4,
    fiber_g: 0.0,
    sugar_g: 2.7,
  },
  {
    name: "quinoa",
    calories: 121.8,
    serving_size_g: 100.0,
    fat_total_g: 1.9,
    fat_saturated_g: 0.2,
    protein_g: 4.4,
    sodium_mg: 6,
    potassium_mg: 152,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21.0,
    fiber_g: 2.8,
    sugar_g: 0.9,
  },
  {
    name: "melons",
    calories: 33.6,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    protein_g: 0.8,
    sodium_mg: 16,
    potassium_mg: 14,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.1,
    fiber_g: 0.9,
    sugar_g: 7.8,
  },
  {
    name: "almond milk",
    calories: 22.0,
    serving_size_g: 100.0,
    fat_total_g: 1.0,
    fat_saturated_g: 0.1,
    protein_g: 0.4,
    sodium_mg: 3,
    potassium_mg: 9,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.2,
    fiber_g: 0.3,
    sugar_g: 2.9,
  },
  {
    name: "spinach",
    calories: 23.3,
    serving_size_g: 100.0,
    fat_total_g: 0.3,
    fat_saturated_g: 0.0,
    protein_g: 2.9,
    sodium_mg: 69,
    potassium_mg: 55,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.8,
    fiber_g: 2.4,
    sugar_g: 0.4,
  },
  {
    name: "apples",
    calories: 53.4,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.3,
    sodium_mg: 1,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.8,
    fiber_g: 2.4,
    sugar_g: 10.3,
  },
  {
    name: "bananas",
    calories: 87.4,
    serving_size_g: 100.0,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    protein_g: 1.1,
    sodium_mg: 1,
    potassium_mg: 22,
    cholesterol_mg: 0,
    carbohydrates_total_g: 22.4,
    fiber_g: 2.6,
    sugar_g: 12.2,
  },
  {
    name: "ribs",
    calories: 361.3,
    serving_size_g: 100.0,
    fat_total_g: 30.9,
    fat_saturated_g: 9.2,
    protein_g: 21.1,
    sodium_mg: 91,
    potassium_mg: 159,
    cholesterol_mg: 103,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "watermelons",
    calories: 30.2,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.6,
    sodium_mg: 0,
    potassium_mg: 11,
    cholesterol_mg: 0,
    carbohydrates_total_g: 7.5,
    fiber_g: 0.4,
    sugar_g: 6.2,
  },
  {
    name: "pasta",
    calories: 156.0,
    serving_size_g: 100.0,
    fat_total_g: 0.9,
    fat_saturated_g: 0.2,
    protein_g: 5.7,
    sodium_mg: 1,
    potassium_mg: 58,
    cholesterol_mg: 0,
    carbohydrates_total_g: 31.3,
    fiber_g: 1.8,
    sugar_g: 0.6,
  },
  {
    name: "peaches",
    calories: 39.5,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.9,
    sodium_mg: 0,
    potassium_mg: 19,
    cholesterol_mg: 0,
    carbohydrates_total_g: 9.7,
    fiber_g: 1.5,
    sugar_g: 8.4,
  },
  {
    name: "cereal",
    calories: 386.0,
    serving_size_g: 100.0,
    fat_total_g: 6.8,
    fat_saturated_g: 1.5,
    protein_g: 12.2,
    sodium_mg: 495,
    potassium_mg: 489,
    cholesterol_mg: 0,
    carbohydrates_total_g: 71.9,
    fiber_g: 9.2,
    sugar_g: 4.3,
  },
  {
    name: "pork",
    calories: 236.2,
    serving_size_g: 100.0,
    fat_total_g: 14.0,
    fat_saturated_g: 4.9,
    protein_g: 26.2,
    sodium_mg: 57,
    potassium_mg: 219,
    cholesterol_mg: 88,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "meatballs",
    calories: 289.2,
    serving_size_g: 100.0,
    fat_total_g: 21.8,
    fat_saturated_g: 7.7,
    protein_g: 14.5,
    sodium_mg: 662,
    potassium_mg: 243,
    cholesterol_mg: 66,
    carbohydrates_total_g: 8.1,
    fiber_g: 2.3,
    sugar_g: 3.5,
  },
  {
    name: "tuna",
    calories: 133.3,
    serving_size_g: 100.0,
    fat_total_g: 0.6,
    fat_saturated_g: 0.2,
    protein_g: 29.4,
    sodium_mg: 54,
    potassium_mg: 331,
    cholesterol_mg: 46,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "onions",
    calories: 44.5,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 1.4,
    sodium_mg: 3,
    potassium_mg: 35,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.2,
    fiber_g: 1.4,
    sugar_g: 4.8,
  },
  {
    name: "pineapples",
    calories: 51.3,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 0.5,
    sodium_mg: 1,
    potassium_mg: 8,
    cholesterol_mg: 0,
    carbohydrates_total_g: 13.1,
    fiber_g: 1.4,
    sugar_g: 9.9,
  },
  {
    name: "carrots",
    calories: 35.1,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.8,
    sodium_mg: 56,
    potassium_mg: 30,
    cholesterol_mg: 0,
    carbohydrates_total_g: 8.1,
    fiber_g: 3.0,
    sugar_g: 3.4,
  },
  {
    name: "bacon",
    calories: 466.4,
    serving_size_g: 100.0,
    fat_total_g: 34.9,
    fat_saturated_g: 12.0,
    protein_g: 34.0,
    sodium_mg: 1674,
    potassium_mg: 380,
    cholesterol_mg: 98,
    carbohydrates_total_g: 1.7,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "ground meat",
    calories: 266.2,
    serving_size_g: 100.0,
    fat_total_g: 17.5,
    fat_saturated_g: 6.6,
    protein_g: 26.9,
    sodium_mg: 89,
    potassium_mg: 225,
    cholesterol_mg: 89,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "shrimps",
    calories: 118.7,
    serving_size_g: 100.0,
    fat_total_g: 1.8,
    fat_saturated_g: 0.6,
    protein_g: 22.8,
    sodium_mg: 930,
    potassium_mg: 307,
    cholesterol_mg: 208,
    carbohydrates_total_g: 1.6,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "bread",
    calories: 261.6,
    serving_size_g: 100.0,
    fat_total_g: 3.4,
    fat_saturated_g: 0.7,
    protein_g: 8.8,
    sodium_mg: 495,
    potassium_mg: 98,
    cholesterol_mg: 0,
    carbohydrates_total_g: 50.2,
    fiber_g: 2.7,
    sugar_g: 5.7,
  },
  {
    name: "sweet potatoes",
    calories: 75.9,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 1.4,
    sodium_mg: 27,
    potassium_mg: 32,
    cholesterol_mg: 0,
    carbohydrates_total_g: 17.6,
    fiber_g: 2.5,
    sugar_g: 5.8,
  },
  {
    name: "crab meat",
    calories: 80.5,
    serving_size_g: 100.0,
    fat_total_g: 0.7,
    fat_saturated_g: 0.2,
    protein_g: 17.9,
    sodium_mg: 402,
    potassium_mg: 235,
    cholesterol_mg: 98,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "corn",
    calories: 93.9,
    serving_size_g: 100.0,
    fat_total_g: 1.5,
    fat_saturated_g: 0.2,
    protein_g: 3.4,
    sodium_mg: 1,
    potassium_mg: 75,
    cholesterol_mg: 0,
    carbohydrates_total_g: 21.0,
    fiber_g: 2.4,
    sugar_g: 4.6,
  },
  {
    name: "limes",
    calories: 29.4,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.7,
    sodium_mg: 2,
    potassium_mg: 17,
    cholesterol_mg: 0,
    carbohydrates_total_g: 10.7,
    fiber_g: 2.8,
    sugar_g: 1.7,
  },
  {
    name: "lemons",
    calories: 28.5,
    serving_size_g: 100.0,
    fat_total_g: 0.3,
    fat_saturated_g: 0.0,
    protein_g: 1.1,
    sodium_mg: 2,
    potassium_mg: 16,
    cholesterol_mg: 0,
    carbohydrates_total_g: 9.4,
    fiber_g: 2.8,
    sugar_g: 2.5,
  },
  {
    name: "cucumbers",
    calories: 15.1,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 0.7,
    sodium_mg: 1,
    potassium_mg: 23,
    cholesterol_mg: 0,
    carbohydrates_total_g: 3.6,
    fiber_g: 0.5,
    sugar_g: 1.7,
  },
  {
    name: "peas",
    calories: 82.4,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 5.4,
    sodium_mg: 3,
    potassium_mg: 117,
    cholesterol_mg: 0,
    carbohydrates_total_g: 15.9,
    fiber_g: 5.4,
    sugar_g: 5.9,
  },
  {
    name: "cauliflower",
    calories: 22.4,
    serving_size_g: 100.0,
    fat_total_g: 0.5,
    fat_saturated_g: 0.1,
    protein_g: 1.8,
    sodium_mg: 14,
    potassium_mg: 31,
    cholesterol_mg: 0,
    carbohydrates_total_g: 4.1,
    fiber_g: 2.3,
    sugar_g: 2.1,
  },
  {
    name: "kale",
    calories: 27.2,
    serving_size_g: 100.0,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 1.9,
    sodium_mg: 23,
    potassium_mg: 28,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.6,
    fiber_g: 2.0,
    sugar_g: 1.3,
  },
  {
    name: "kiwi",
    calories: 59.5,
    serving_size_g: 100.0,
    fat_total_g: 0.5,
    fat_saturated_g: 0.0,
    protein_g: 1.1,
    sodium_mg: 3,
    potassium_mg: 33,
    cholesterol_mg: 0,
    carbohydrates_total_g: 14.9,
    fiber_g: 3.0,
    sugar_g: 9.1,
  },
  {
    name: "camembert",
    calories: 293.2,
    serving_size_g: 100.0,
    fat_total_g: 24.1,
    fat_saturated_g: 15.4,
    protein_g: 19.9,
    sodium_mg: 826,
    potassium_mg: 349,
    cholesterol_mg: 70,
    carbohydrates_total_g: 0.5,
    fiber_g: 0.0,
    sugar_g: 0.5,
  },
  {
    name: "plums",
    calories: 46.6,
    serving_size_g: 100.0,
    fat_total_g: 0.3,
    fat_saturated_g: 0.0,
    protein_g: 0.7,
    sodium_mg: 0,
    potassium_mg: 15,
    cholesterol_mg: 0,
    carbohydrates_total_g: 11.6,
    fiber_g: 1.4,
    sugar_g: 9.9,
  },
  {
    name: "oats",
    calories: 386.8,
    serving_size_g: 100.0,
    fat_total_g: 6.6,
    fat_saturated_g: 1.1,
    protein_g: 13.3,
    sodium_mg: 5,
    potassium_mg: 417,
    cholesterol_mg: 0,
    carbohydrates_total_g: 68.0,
    fiber_g: 10.2,
    sugar_g: 1.0,
  },
  {
    name: "peppers",
    calories: 27.6,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.0,
    protein_g: 0.9,
    sodium_mg: 2,
    potassium_mg: 17,
    cholesterol_mg: 0,
    carbohydrates_total_g: 6.7,
    fiber_g: 1.2,
    sugar_g: 3.2,
  },
  {
    name: "lamb",
    calories: 301.2,
    serving_size_g: 100.0,
    fat_total_g: 20.5,
    fat_saturated_g: 8.8,
    protein_g: 24.4,
    sodium_mg: 71,
    potassium_mg: 187,
    cholesterol_mg: 98,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "peanut oil",
    calories: 883.0,
    serving_size_g: 100.0,
    fat_total_g: 98.9,
    fat_saturated_g: 16.9,
    protein_g: 0.0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "coconuts",
    calories: 450.1,
    serving_size_g: 100.0,
    fat_total_g: 27.9,
    fat_saturated_g: 26.6,
    protein_g: 3.1,
    sodium_mg: 282,
    potassium_mg: 100,
    cholesterol_mg: 0,
    carbohydrates_total_g: 51.6,
    fiber_g: 9.7,
    sugar_g: 36.8,
  },
  {
    name: "chicken",
    calories: 222.6,
    serving_size_g: 100.0,
    fat_total_g: 12.9,
    fat_saturated_g: 3.7,
    protein_g: 23.7,
    sodium_mg: 72,
    potassium_mg: 179,
    cholesterol_mg: 92,
    carbohydrates_total_g: 0.0,
    fiber_g: 0.0,
    sugar_g: 0.0,
  },
  {
    name: "pistachios",
    calories: 584.0,
    serving_size_g: 100.0,
    fat_total_g: 44.9,
    fat_saturated_g: 5.7,
    protein_g: 21.5,
    sodium_mg: 432,
    potassium_mg: 471,
    cholesterol_mg: 0,
    carbohydrates_total_g: 27.2,
    fiber_g: 10.0,
    sugar_g: 7.1,
  },
  {
    name: "poppy seeds",
    calories: 534.4,
    serving_size_g: 100.0,
    fat_total_g: 40.7,
    fat_saturated_g: 4.7,
    protein_g: 18.0,
    sodium_mg: 26,
    potassium_mg: 861,
    cholesterol_mg: 0,
    carbohydrates_total_g: 28.2,
    fiber_g: 19.3,
    sugar_g: 2.9,
  },
  {
    name: "grapes",
    calories: 69.6,
    serving_size_g: 100.0,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    protein_g: 0.7,
    sodium_mg: 2,
    potassium_mg: 20,
    cholesterol_mg: 0,
    carbohydrates_total_g: 18.1,
    fiber_g: 0.9,
    sugar_g: 15.5,
  },
  {
    name: "croutons",
    calories: 459.5,
    serving_size_g: 100.0,
    fat_total_g: 18.3,
    fat_saturated_g: 5.3,
    protein_g: 10.7,
    sodium_mg: 1089,
    potassium_mg: 139,
    cholesterol_mg: 6,
    carbohydrates_total_g: 64.7,
    fiber_g: 4.9,
    sugar_g: 4.5,
  },
  {
    name: "raspberries",
    calories: 51.8,
    serving_size_g: 100.0,
    fat_total_g: 0.5,
    fat_saturated_g: 0.0,
    protein_g: 1.0,
    sodium_mg: 0,
    potassium_mg: 28,
    cholesterol_mg: 0,
    carbohydrates_total_g: 12.0,
    fiber_g: 6.4,
    sugar_g: 4.5,
  },
  {
    name: "sausages",
    calories: 323.2,
    serving_size_g: 100.0,
    fat_total_g: 26.9,
    fat_saturated_g: 8.7,
    protein_g: 18.6,
    sodium_mg: 808,
    potassium_mg: 150,
    cholesterol_mg: 86,
    carbohydrates_total_g: 1.4,
    fiber_g: 0.0,
    sugar_g: 1.1,
  },
  {
    name: "cabbage",
    calories: 23.4,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 1.3,
    sodium_mg: 7,
    potassium_mg: 32,
    cholesterol_mg: 0,
    carbohydrates_total_g: 5.5,
    fiber_g: 1.9,
    sugar_g: 2.8,
  },
  {
    name: "granola",
    calories: 475.7,
    serving_size_g: 100.0,
    fat_total_g: 23.9,
    fat_saturated_g: 4.0,
    protein_g: 13.6,
    sodium_mg: 25,
    potassium_mg: 432,
    cholesterol_mg: 0,
    carbohydrates_total_g: 54.3,
    fiber_g: 9.0,
    sugar_g: 20.0,
  },
  {
    name: "zucchinis",
    calories: 14.7,
    serving_size_g: 100.0,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    protein_g: 1.1,
    sodium_mg: 3,
    potassium_mg: 37,
    cholesterol_mg: 0,
    carbohydrates_total_g: 2.7,
    fiber_g: 1.0,
    sugar_g: 1.7,
  },
  {
    name: "protein powder",
    calories: 348.4,
    serving_size_g: 100.0,
    fat_total_g: 1.5,
    fat_saturated_g: 0.8,
    protein_g: 77.9,
    sodium_mg: 158,
    potassium_mg: 1310,
    cholesterol_mg: 16,
    carbohydrates_total_g: 6.2,
    fiber_g: 3.1,
    sugar_g: 0.0,
  },
  {
    name: "whipped cream",
    calories: 260.9,
    serving_size_g: 100.0,
    fat_total_g: 22.0,
    fat_saturated_g: 13.7,
    protein_g: 3.1,
    sodium_mg: 8,
    potassium_mg: 87,
    cholesterol_mg: 77,
    carbohydrates_total_g: 12.7,
    fiber_g: 0.0,
    sugar_g: 8.1,
  },
  {
    name: "molasses",
    calories: 287.4,
    serving_size_g: 100.0,
    fat_total_g: 0.1,
    fat_saturated_g: 0.0,
    protein_g: 0.0,
    sodium_mg: 36,
    potassium_mg: 30,
    cholesterol_mg: 0,
    carbohydrates_total_g: 75.9,
    fiber_g: 0.0,
    sugar_g: 74.4,
  },
];

[
    {
      name: 'eggplants',
      calories: 35.5,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 0.8,
      sodium_mg: 0,
      potassium_mg: 15,
      cholesterol_mg: 0,
      carbohydrates_total_g: 8.9,
      fiber_g: 2.5,
      sugar_g: 3.2,
    },
    ,
    {
      name: 'bacon',
      calories: 466.4,
      serving_size_g: 100.0,
      fat_total_g: 34.9,
      fat_saturated_g: 12.0,
      protein_g: 34.0,
      sodium_mg: 1674,
      potassium_mg: 380,
      cholesterol_mg: 98,
      carbohydrates_total_g: 1.7,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'peaches',
      calories: 39.5,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 0.9,
      sodium_mg: 0,
      potassium_mg: 19,
      cholesterol_mg: 0,
      carbohydrates_total_g: 9.7,
      fiber_g: 1.5,
      sugar_g: 8.4,
    },
    {
      name: 'avocados',
      calories: 171.9,
      serving_size_g: 100.0,
      fat_total_g: 15.3,
      fat_saturated_g: 2.1,
      protein_g: 2.0,
      sodium_mg: 7,
      potassium_mg: 53,
      cholesterol_mg: 0,
      carbohydrates_total_g: 8.6,
      fiber_g: 6.7,
      sugar_g: 0.3,
    },
    {
      name: 'pasta',
      calories: 156.0,
      serving_size_g: 100.0,
      fat_total_g: 0.9,
      fat_saturated_g: 0.2,
      protein_g: 5.7,
      sodium_mg: 1,
      potassium_mg: 58,
      cholesterol_mg: 0,
      carbohydrates_total_g: 31.3,
      fiber_g: 1.8,
      sugar_g: 0.6,
    },
    {
      name: 'ham',
      calories: 141.6,
      serving_size_g: 100.0,
      fat_total_g: 5.1,
      fat_saturated_g: 0.9,
      protein_g: 22.2,
      sodium_mg: 968,
      potassium_mg: 305,
      cholesterol_mg: 64,
      carbohydrates_total_g: 1.0,
      fiber_g: 0.0,
      sugar_g: 1.1,
    },
    {
      name: 'cream',
      calories: 347.4,
      serving_size_g: 100.0,
      fat_total_g: 35.6,
      fat_saturated_g: 22.9,
      protein_g: 2.9,
      sodium_mg: 27,
      potassium_mg: 57,
      cholesterol_mg: 111,
      carbohydrates_total_g: 2.8,
      fiber_g: 0.0,
      sugar_g: 2.9,
    },
    {
      name: 'zucchinis',
      calories: 14.7,
      serving_size_g: 100.0,
      fat_total_g: 0.4,
      fat_saturated_g: 0.1,
      protein_g: 1.1,
      sodium_mg: 3,
      potassium_mg: 37,
      cholesterol_mg: 0,
      carbohydrates_total_g: 2.7,
      fiber_g: 1.0,
      sugar_g: 1.7,
    },
    {
      name: 'carrots',
      calories: 35.1,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 0.8,
      sodium_mg: 56,
      potassium_mg: 30,
      cholesterol_mg: 0,
      carbohydrates_total_g: 8.1,
      fiber_g: 3.0,
      sugar_g: 3.4,
    },
    {
      name: 'limes',
      calories: 29.4,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 0.7,
      sodium_mg: 2,
      potassium_mg: 17,
      cholesterol_mg: 0,
      carbohydrates_total_g: 10.7,
      fiber_g: 2.8,
      sugar_g: 1.7,
    },
    {
      name: 'sesame seeds',
      calories: 575.8,
      serving_size_g: 100.0,
      fat_total_g: 49.0,
      fat_saturated_g: 6.8,
      protein_g: 17.0,
      sodium_mg: 11,
      potassium_mg: 629,
      cholesterol_mg: 0,
      carbohydrates_total_g: 26.2,
      fiber_g: 14.0,
      sugar_g: 0.0,
    },
    {
      name: 'spinach',
      calories: 23.3,
      serving_size_g: 100.0,
      fat_total_g: 0.3,
      fat_saturated_g: 0.0,
      protein_g: 2.9,
      sodium_mg: 69,
      potassium_mg: 55,
      cholesterol_mg: 0,
      carbohydrates_total_g: 3.8,
      fiber_g: 2.4,
      sugar_g: 0.4,
    },
    {
      name: 'pork',
      calories: 236.2,
      serving_size_g: 100.0,
      fat_total_g: 14.0,
      fat_saturated_g: 4.9,
      protein_g: 26.2,
      sodium_mg: 57,
      potassium_mg: 219,
      cholesterol_mg: 88,
      carbohydrates_total_g: 0.0,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'chicken',
      calories: 222.6,
      serving_size_g: 100.0,
      fat_total_g: 12.9,
      fat_saturated_g: 3.7,
      protein_g: 23.7,
      sodium_mg: 72,
      potassium_mg: 179,
      cholesterol_mg: 92,
      carbohydrates_total_g: 0.0,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'cauliflower',
      calories: 22.4,
      serving_size_g: 100.0,
      fat_total_g: 0.5,
      fat_saturated_g: 0.1,
      protein_g: 1.8,
      sodium_mg: 14,
      potassium_mg: 31,
      cholesterol_mg: 0,
      carbohydrates_total_g: 4.1,
      fiber_g: 2.3,
      sugar_g: 2.1,
    },
    {
      name: 'grapefruits',
      calories: 43.2,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 0.8,
      sodium_mg: 0,
      potassium_mg: 18,
      cholesterol_mg: 0,
      carbohydrates_total_g: 10.7,
      fiber_g: 1.6,
      sugar_g: 6.9,
    },
    {
      name: 'garlic',
      calories: 144.8,
      serving_size_g: 100.0,
      fat_total_g: 0.7,
      fat_saturated_g: 0.0,
      protein_g: 6.4,
      sodium_mg: 16,
      potassium_mg: 153,
      cholesterol_mg: 0,
      carbohydrates_total_g: 32.5,
      fiber_g: 2.0,
      sugar_g: 1.0,
    },
    {
      name: 'turkey',
      calories: 193.1,
      serving_size_g: 100.0,
      fat_total_g: 7.4,
      fat_saturated_g: 2.2,
      protein_g: 28.6,
      sodium_mg: 104,
      potassium_mg: 226,
      cholesterol_mg: 110,
      carbohydrates_total_g: 0.1,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'mangoes',
      calories: 58.7,
      serving_size_g: 100.0,
      fat_total_g: 0.4,
      fat_saturated_g: 0.1,
      protein_g: 0.8,
      sodium_mg: 1,
      potassium_mg: 13,
      cholesterol_mg: 0,
      carbohydrates_total_g: 15.1,
      fiber_g: 1.6,
      sugar_g: 13.7,
    },
    {
      name: 'kale',
      calories: 27.2,
      serving_size_g: 100.0,
      fat_total_g: 0.4,
      fat_saturated_g: 0.1,
      protein_g: 1.9,
      sodium_mg: 23,
      potassium_mg: 28,
      cholesterol_mg: 0,
      carbohydrates_total_g: 5.6,
      fiber_g: 2.0,
      sugar_g: 1.3,
    },
    {
      name: 'lettuce',
      calories: 17.0,
      serving_size_g: 100.0,
      fat_total_g: 0.3,
      fat_saturated_g: 0.0,
      protein_g: 1.2,
      sodium_mg: 7,
      potassium_mg: 30,
      cholesterol_mg: 0,
      carbohydrates_total_g: 3.3,
      fiber_g: 2.1,
      sugar_g: 1.2,
    },
    {
      name: 'tuna',
      calories: 133.3,
      serving_size_g: 100.0,
      fat_total_g: 0.6,
      fat_saturated_g: 0.2,
      protein_g: 29.4,
      sodium_mg: 54,
      potassium_mg: 331,
      cholesterol_mg: 46,
      carbohydrates_total_g: 0.0,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'crab meat',
      calories: 80.5,
      serving_size_g: 100.0,
      fat_total_g: 0.7,
      fat_saturated_g: 0.2,
      protein_g: 17.9,
      sodium_mg: 402,
      potassium_mg: 235,
      cholesterol_mg: 98,
      carbohydrates_total_g: 0.0,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'pretzels',
      calories: 389.1,
      serving_size_g: 100.0,
      fat_total_g: 2.9,
      fat_saturated_g: 0.4,
      protein_g: 10.1,
      sodium_mg: 1216,
      potassium_mg: 127,
      cholesterol_mg: 0,
      carbohydrates_total_g: 81.2,
      fiber_g: 3.4,
      sugar_g: 2.2,
    },
    {
      name: 'bananas',
      calories: 87.4,
      serving_size_g: 100.0,
      fat_total_g: 0.3,
      fat_saturated_g: 0.1,
      protein_g: 1.1,
      sodium_mg: 1,
      potassium_mg: 22,
      cholesterol_mg: 0,
      carbohydrates_total_g: 22.4,
      fiber_g: 2.6,
      sugar_g: 12.2,
    },
    {
      name: 'plums',
      calories: 46.6,
      serving_size_g: 100.0,
      fat_total_g: 0.3,
      fat_saturated_g: 0.0,
      protein_g: 0.7,
      sodium_mg: 0,
      potassium_mg: 15,
      cholesterol_mg: 0,
      carbohydrates_total_g: 11.6,
      fiber_g: 1.4,
      sugar_g: 9.9,
    },
    {
      name: 'lamb',
      calories: 301.2,
      serving_size_g: 100.0,
      fat_total_g: 20.5,
      fat_saturated_g: 8.8,
      protein_g: 24.4,
      sodium_mg: 71,
      potassium_mg: 187,
      cholesterol_mg: 98,
      carbohydrates_total_g: 0.0,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'cucumbers',
      calories: 15.1,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 0.7,
      sodium_mg: 1,
      potassium_mg: 23,
      cholesterol_mg: 0,
      carbohydrates_total_g: 3.6,
      fiber_g: 0.5,
      sugar_g: 1.7,
    },
    {
      name: 'peas',
      calories: 82.4,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 5.4,
      sodium_mg: 3,
      potassium_mg: 117,
      cholesterol_mg: 0,
      carbohydrates_total_g: 15.9,
      fiber_g: 5.4,
      sugar_g: 5.9,
    },
    {
      name: 'melons',
      calories: 33.6,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.1,
      protein_g: 0.8,
      sodium_mg: 16,
      potassium_mg: 14,
      cholesterol_mg: 0,
      carbohydrates_total_g: 8.1,
      fiber_g: 0.9,
      sugar_g: 7.8,
    },
    {
      name: 'scallops',
      calories: 110.3,
      serving_size_g: 100.0,
      fat_total_g: 0.9,
      fat_saturated_g: 0.2,
      protein_g: 20.5,
      sodium_mg: 660,
      potassium_mg: 421,
      cholesterol_mg: 40,
      carbohydrates_total_g: 5.4,
      fiber_g: 0.0,
      sugar_g: 0.0,
    },
    {
      name: 'kiwi',
      calories: 59.5,
      serving_size_g: 100.0,
      fat_total_g: 0.5,
      fat_saturated_g: 0.0,
      protein_g: 1.1,
      sodium_mg: 3,
      potassium_mg: 33,
      cholesterol_mg: 0,
      carbohydrates_total_g: 14.9,
      fiber_g: 3.0,
      sugar_g: 9.1,
    },
    {
      name: 'cornmeal',
      calories: 368.6,
      serving_size_g: 100.0,
      fat_total_g: 3.5,
      fat_saturated_g: 0.5,
      protein_g: 8.1,
      sodium_mg: 34,
      potassium_mg: 237,
      cholesterol_mg: 0,
      carbohydrates_total_g: 76.1,
      fiber_g: 7.3,
      sugar_g: 0.6,
    },
    {
      name: 'corn',
      calories: 93.9,
      serving_size_g: 100.0,
      fat_total_g: 1.5,
      fat_saturated_g: 0.2,
      protein_g: 3.4,
      sodium_mg: 1,
      potassium_mg: 75,
      cholesterol_mg: 0,
      carbohydrates_total_g: 21.0,
      fiber_g: 2.4,
      sugar_g: 4.6,
    },
    {
      name: 'peppers',
      calories: 27.6,
      serving_size_g: 100.0,
      fat_total_g: 0.2,
      fat_saturated_g: 0.0,
      protein_g: 0.9,
      sodium_mg: 2,
      potassium_mg: 17,
      cholesterol_mg: 0,
      carbohydrates_total_g: 6.7,
      fiber_g: 1.2,
      sugar_g: 3.2,
    },
    {
      name: 'cheese',
      calories: 393.9,
      serving_size_g: 100.0,
      fat_total_g: 33.0,
      fat_saturated_g: 18.9,
      protein_g: 22.7,
      sodium_mg: 661,
      potassium_mg: 459,
      cholesterol_mg: 100,
      carbohydrates_total_g: 3.2,
      fiber_g: 0.0,
      sugar_g: 0.5,
    },
    {
      name: 'cabbage',
      calories: 23.4,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 1.3,
      sodium_mg: 7,
      potassium_mg: 32,
      cholesterol_mg: 0,
      carbohydrates_total_g: 5.5,
      fiber_g: 1.9,
      sugar_g: 2.8,
    },
    {
      name: 'coconuts',
      calories: 450.1,
      serving_size_g: 100.0,
      fat_total_g: 27.9,
      fat_saturated_g: 26.6,
      protein_g: 3.1,
      sodium_mg: 282,
      potassium_mg: 100,
      cholesterol_mg: 0,
      carbohydrates_total_g: 51.6,
      fiber_g: 9.7,
      sugar_g: 36.8,
    },
    {
      name: 'blueberries',
      calories: 55.7,
      serving_size_g: 100.0,
      fat_total_g: 0.0,
      fat_saturated_g: 0.0,
      protein_g: 0.7,
      sodium_mg: 0,
      potassium_mg: 11,
      cholesterol_mg: 0,
      carbohydrates_total_g: 14.8,
      fiber_g: 2.2,
      sugar_g: 10.3,
    },
    {
      name: 'mascarpone',
      calories: 444.5,
      serving_size_g: 100.0,
      fat_total_g: 45.6,
      fat_saturated_g: 27.3,
      protein_g: 4.6,
      sodium_mg: 431,
      potassium_mg: 84,
      cholesterol_mg: 134,
      carbohydrates_total_g: 3.0,
      fiber_g: 0.0,
      sugar_g: 2.4,
    },
    {
      name: 'sweet potatoes',
      calories: 75.9,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 1.4,
      sodium_mg: 27,
      potassium_mg: 32,
      cholesterol_mg: 0,
      carbohydrates_total_g: 17.6,
      fiber_g: 2.5,
      sugar_g: 5.8,
    },
    {
      name: 'pineapples',
      calories: 51.3,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 0.5,
      sodium_mg: 1,
      potassium_mg: 8,
      cholesterol_mg: 0,
      carbohydrates_total_g: 13.1,
      fiber_g: 1.4,
      sugar_g: 9.9,
    },
    {
      name: 'blue cheese',
      calories: 346.9,
      serving_size_g: 100.0,
      fat_total_g: 28.9,
      fat_saturated_g: 18.5,
      protein_g: 21.6,
      sodium_mg: 1156,
      potassium_mg: 384,
      cholesterol_mg: 76,
      carbohydrates_total_g: 2.3,
      fiber_g: 0.0,
      sugar_g: 0.5,
    },
    {
      name: 'cottage cheese',
      calories: 98.3,
      serving_size_g: 100.0,
      fat_total_g: 4.3,
      fat_saturated_g: 1.7,
      protein_g: 11.2,
      sodium_mg: 370,
      potassium_mg: 161,
      cholesterol_mg: 16,
      carbohydrates_total_g: 3.4,
      fiber_g: 0.0,
      sugar_g: 2.7,
    },
    {
      name: 'strawberries',
      calories: 31.3,
      serving_size_g: 100.0,
      fat_total_g: 0.3,
      fat_saturated_g: 0.0,
      protein_g: 0.7,
      sodium_mg: 1,
      potassium_mg: 23,
      cholesterol_mg: 0,
      carbohydrates_total_g: 7.6,
      fiber_g: 2.0,
      sugar_g: 4.9,
    },
    {
      name: 'juice',
      calories: 53.7,
      serving_size_g: 100.0,
      fat_total_g: 0.0,
      fat_saturated_g: 0.0,
      protein_g: 0.1,
      sodium_mg: 61,
      potassium_mg: 6,
      cholesterol_mg: 0,
      carbohydrates_total_g: 13.3,
      fiber_g: 0.1,
      sugar_g: 12.2,
    },
    {
      name: 'cocktail',
      calories: 139.7,
      serving_size_g: 100.0,
      fat_total_g: 0.1,
      fat_saturated_g: 0.0,
      protein_g: 0.2,
      sodium_mg: 1,
      potassium_mg: 8,
      cholesterol_mg: 0,
      carbohydrates_total_g: 8.7,
      fiber_g: 0.1,
      sugar_g: 8.4,
    },
  ];
  
