version: '3.9'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # postgres
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: challenge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  training-db:
    container_name: training-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: trainingdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'


  # mongo-db
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'

