-- AlterTable
ALTER TABLE "Ingredients" ALTER COLUMN "grammes" SET DEFAULT 100,
ALTER COLUMN "grammes" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fat_total_g" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fat_saturated_g" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "protein_g" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sodium_mg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "potassium_mg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "cholesterol_mg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carbohydrates_total_g" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fiber_g" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sugar_g" SET DATA TYPE DOUBLE PRECISION;
